### ISSUE TITLE
Not Compatible with Laravel-admin 1.8.*

### ISSUE THREAD

**Issue by bachtiarpanjaitan** [laravel-admin-extensions/api-tester#13]
I got error while trying to install api-tester on Laravel-admin 1.8.*

`Problem 1
    - Installation request for laravel/framework (locked at v6.18.26, required as ^6.2) -> satisfiable by laravel/framework[v6.18.26].
    - Installation request for laravel-admin-ext/api-tester ^1.0 -> satisfiable by laravel-admin-ext/api-tester[v1.0, v1.0.1, v1.0.2].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.8.1].
    - Can only install one of: encore/laravel-admin[v1.8.1, 1.5.x-dev].
    - Can only install one of: encore/laravel-admin[1.5.x-dev, v1.8.1].
    - Conclusion: install encore/laravel-admin 1.5.x-dev
    - Installation request for encore/laravel-admin 1.8.1 -> satisfiable by encore/laravel-admin[v1.8.1].`

**Comment by z-song** [comment]
Install version v1.0.4
